version: '3.8'

services:
  transfixer:
    build: .
    container_name: transfixer
    volumes:
      - ./audio:/app/audio
      - ./transcriptions:/app/transcriptions
      - ./corrected:/app/corrected
      - ./logs:/app/logs
      - ./backup:/app/backup
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped 